import type { AtlasDef } from "../atlasConfig.ts";

export const DesertAtlas: AtlasDef = {
    compress: true,
    images: [
        "map/map-archway-res-01.svg",
        "map/map-building-archway-ceiling-01.svg",
        "map/map-building-greenhouse-ceiling-02.svg",
        "map/map-building-greenhouse-floor-02.svg",
        "map/map-building-saloon-ceiling-01.svg",
        "map/map-building-saloon-ceiling-02.svg",
        "map/map-building-saloon-cellar-01.svg",
        "map/map-building-saloon-floor-01.svg",
        "map/map-bunker-chrys-chamber-ceiling-01.svg",
        "map/map-bunker-chrys-chamber-floor-01a.svg",
        "map/map-bunker-chrys-chamber-floor-01b.svg",
        "map/map-bunker-chrys-compartment-ceiling-01a.svg",
        "map/map-bunker-chrys-compartment-ceiling-01b.svg",
        "map/map-bunker-chrys-compartment-ceiling-02a.svg",
        "map/map-bunker-chrys-compartment-ceiling-02b.svg",
        "map/map-bunker-chrys-compartment-ceiling-03a.svg",
        "map/map-bunker-chrys-compartment-ceiling-03b.svg",
        "map/map-bunker-chrys-compartment-floor-01a.svg",
        "map/map-bunker-chrys-compartment-floor-01c.svg",
        "map/map-bunker-chrys-compartment-floor-02a.svg",
        "map/map-bunker-chrys-compartment-floor-02c.svg",
        "map/map-bunker-chrys-compartment-floor-03a.svg",
        "map/map-bunker-generic-ceiling-02.svg",
        "map/map-bunker-generic-floor-03.svg",
        "map/map-bunker-statue-chamber-floor-01.svg",
        "map/map-bush-05.svg",
        "map/map-bush-res-05.svg",
        "map/map-case-meteor-01.svg",
        "map/map-case-meteor-res-01.svg",
        "map/map-chest-03d.svg",
        "map/map-complex-warehouse-floor-05.svg",
        "map/map-crate-02f.svg",
        "map/map-crate-18.svg",
        "map/map-crate-22.svg",
        "map/map-planter-06.svg",
        "map/map-planter-07.svg",
        "map/map-planter-res-02.svg",
        "map/map-planter-res-03.svg",
        "map/map-statue-03.svg",
        "map/map-statue-04.svg",
        "map/map-stone-03b.svg",
        "map/map-stone-06.svg",
        "map/map-stone-res-01b.svg",
        "map/map-tree-05c.svg",
        "map/map-tree-06.svg",
    ],
};
