import type { AtlasDef } from "../atlasConfig.ts";

export const FactionAtlas: AtlasDef = {
    compress: true,
    images: [
        "map/map-airdrop-03.svg",
        "map/map-airdrop-04.svg",
        "map/map-building-bridge-xlg-floor.svg",
        "map/map-building-greenhouse-ceiling-01.svg",
        "map/map-building-greenhouse-floor-01.svg",
        "map/map-bunker-chrys-chamber-ceiling-01.svg",
        "map/map-bunker-chrys-chamber-floor-01a.svg",
        "map/map-bunker-chrys-chamber-floor-01b.svg",
        "map/map-bunker-chrys-compartment-ceiling-01a.svg",
        "map/map-bunker-chrys-compartment-ceiling-01b.svg",
        "map/map-bunker-chrys-compartment-ceiling-02a.svg",
        "map/map-bunker-chrys-compartment-ceiling-02b.svg",
        "map/map-bunker-chrys-compartment-ceiling-03a.svg",
        "map/map-bunker-chrys-compartment-ceiling-03b.svg",
        "map/map-bunker-chrys-compartment-floor-01a.svg",
        "map/map-bunker-chrys-compartment-floor-01b.svg",
        "map/map-bunker-chrys-compartment-floor-02a.svg",
        "map/map-bunker-chrys-compartment-floor-02b.svg",
        "map/map-bunker-chrys-compartment-floor-03a.svg",
        "map/map-bunker-generic-ceiling-02.svg",
        "map/map-bunker-generic-floor-03.svg",
        "map/map-chest-03f.svg",
        "map/map-complex-warehouse-floor-01.svg",
        "map/map-complex-warehouse-floor-02.svg",
        "map/map-complex-warehouse-floor-03.svg",
        "map/map-complex-warehouse-floor-04.svg",
        "map/map-crate-02f.svg",
        "map/map-crate-12.svg",
        "map/map-crate-13.svg",
        "map/map-crate-22.svg",
        "map/map-planter-01.svg",
        "map/map-planter-02.svg",
        "map/map-planter-03.svg",
        "map/map-planter-04.svg",
        "map/map-planter-05.svg",
        "map/map-planter-res-01.svg",
        "map/map-statue-01.svg",
        "map/map-statue-top-01.svg",
        "map/map-statue-top-02.svg",
        "map/map-stone-03f.svg",
        "map/map-stone-res-02f.svg",
    ],
};
