import type { AtlasDef } from "../atlasConfig.ts";

export const HalloweenAtlas: AtlasDef = {
    compress: true,
    images: [
        "map/map-airdrop-01h.svg",
        "map/map-airdrop-02h.svg",
        "map/map-bunker-eye-chamber-ceiling-01.svg",
        "map/map-bunker-eye-chamber-floor-01a.svg",
        "map/map-bunker-eye-chamber-floor-01b.svg",
        "map/map-bunker-eye-compartment-ceiling-01.svg",
        "map/map-bunker-eye-compartment-floor-01.svg",
        "map/map-bush-06.svg",
        "map/map-bush-07sp.svg",
        "map/map-bush-res-06.svg",
        "map/map-crate-11h.svg",
        "map/map-pumpkin-01.svg",
        "map/map-pumpkin-02.svg",
        "map/map-pumpkin-03.svg",
        "map/map-pumpkin-res-01.svg",
        "map/map-pumpkin-res-03.svg",
        "map/map-tree-04h.svg",
        "map/map-tree-05.svg",
        "map/map-tree-07.svg",
        "map/map-tree-08.svg",
        "map/map-web-01.svg",
        "particles/part-airdrop-01h.svg",
        "particles/part-airdrop-02h.svg",
    ],
};
