packages:
  - server/
  - shared/
  - client/
  - client/atlas-builder
  - '!**dist/**'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@taufik-nurrohman/color-picker'
  - better-sqlite3
  - canvas
  - esbuild
  - sharp
