import type { MatchData } from "../../server/src/api/routes/stats/match_data";

const one: MatchData[] = [
    {
        slug: "yte",
        username: "cziesnok",
        player_id: 32,
        team_id: 12,
        time_alive: 178,
        rank: 1,
        died: true,
        kills: 3,
        damage_dealt: 506,
        damage_taken: 156,
        killer_id: 3,
        killed_ids: [15, 39, 2],
    },
    {
        slug: "shiny_fox",
        username: "{SW}FallenAngel",
        player_id: 31,
        team_id: 12,
        time_alive: 249,
        rank: 1,
        died: true,
        kills: 0,
        damage_dealt: 596,
        damage_taken: 308,
        killer_id: 3,
        killed_ids: [],
    },
    {
        slug: "team-kirill2007",
        username: "Bouchik {SW}",
        player_id: 30,
        team_id: 12,
        time_alive: 179,
        rank: 1,
        died: true,
        kills: 3,
        damage_dealt: 411,
        damage_taken: 101,
        killer_id: 46,
        killed_ids: [36, 40, 42],
    },
    {
        slug: "evzinplay",
        username: "~ggman:D~ {SW}",
        player_id: 34,
        team_id: 12,
        time_alive: 366,
        rank: 1,
        died: false,
        kills: 9,
        damage_dealt: 1034,
        damage_taken: 364,
        killer_id: 0,
        killed_ids: [28, 35, 1, 48, 51, 59, 3, 14, 61],
    },
    {
        slug: null,
        username: "ZIPO",
        player_id: 60,
        team_id: 19,
        time_alive: 37,
        rank: 2,
        died: true,
        kills: 0,
        damage_dealt: 116,
        damage_taken: 101,
        killer_id: 37,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Player",
        player_id: 59,
        team_id: 19,
        time_alive: 256,
        rank: 2,
        died: true,
        kills: 1,
        damage_dealt: 100,
        damage_taken: 124,
        killer_id: 34,
        killed_ids: [74],
    },
    {
        slug: null,
        username: "Why? Why? Why?",
        player_id: 61,
        team_id: 19,
        time_alive: 345,
        rank: 2,
        died: true,
        kills: 3,
        damage_dealt: 279,
        damage_taken: 176,
        killer_id: 34,
        killed_ids: [79, 5, 6],
    },
    {
        slug: null,
        username: "guga",
        player_id: 62,
        team_id: 19,
        time_alive: 53,
        rank: 2,
        died: true,
        kills: 0,
        damage_dealt: 53,
        damage_taken: 100,
        killer_id: 79,
        killed_ids: [],
    },
    {
        slug: null,
        username: "ANITA",
        player_id: 16,
        team_id: 4,
        time_alive: 67,
        rank: 3,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 39,
        killed_ids: [],
    },
    {
        slug: null,
        username: "XD",
        player_id: 13,
        team_id: 4,
        time_alive: 126,
        rank: 3,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 124,
        killer_id: 68,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Player",
        player_id: 14,
        team_id: 4,
        time_alive: 373,
        rank: 3,
        died: true,
        kills: 5,
        damage_dealt: 930,
        damage_taken: 442,
        killer_id: 34,
        killed_ids: [57, 10, 9, 45, 68],
    },
    {
        slug: null,
        username: "KATKA",
        player_id: 15,
        team_id: 4,
        time_alive: 84,
        rank: 3,
        died: true,
        kills: 0,
        damage_dealt: 25,
        damage_taken: 100,
        killer_id: 32,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Player",
        player_id: 1,
        team_id: 1,
        time_alive: 170,
        rank: 4,
        died: true,
        kills: 0,
        damage_dealt: 198,
        damage_taken: 139,
        killer_id: 34,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Minni",
        player_id: 2,
        team_id: 1,
        time_alive: 188,
        rank: 4,
        died: true,
        kills: 1,
        damage_dealt: 99,
        damage_taken: 100,
        killer_id: 32,
        killed_ids: [7],
    },
    {
        slug: null,
        username: "Player",
        player_id: 4,
        team_id: 1,
        time_alive: 59,
        rank: 4,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 4,
        killed_ids: [],
    },
    {
        slug: "imgood3",
        username: "warm up:)",
        player_id: 3,
        team_id: 1,
        time_alive: 342,
        rank: 4,
        died: true,
        kills: 10,
        damage_dealt: 1568,
        damage_taken: 354,
        killer_id: 34,
        killed_ids: [17, 69, 70, 18, 47, 32, 46, 44, 31, 49],
    },
    {
        slug: null,
        username: "Rohanskiy",
        player_id: 51,
        team_id: 16,
        time_alive: 244,
        rank: 5,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 34,
        killed_ids: [],
    },
    {
        slug: null,
        username: "POLAK",
        player_id: 47,
        team_id: 16,
        time_alive: 108,
        rank: 5,
        died: true,
        kills: 0,
        damage_dealt: 15,
        damage_taken: 100,
        killer_id: 3,
        killed_ids: [],
    },
    {
        slug: "ali278",
        username: "AL0",
        player_id: 48,
        team_id: 16,
        time_alive: 221,
        rank: 5,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 104,
        killer_id: 34,
        killed_ids: [],
    },
    {
        slug: null,
        username: "matthIS",
        player_id: 49,
        team_id: 16,
        time_alive: 258,
        rank: 5,
        died: true,
        kills: 0,
        damage_dealt: 7,
        damage_taken: 187,
        killer_id: 3,
        killed_ids: [],
    },
    {
        slug: "goldentfm",
        username: "Lil_Saek007",
        player_id: 68,
        team_id: 22,
        time_alive: 242,
        rank: 6,
        died: true,
        kills: 2,
        damage_dealt: 216,
        damage_taken: 248,
        killer_id: 14,
        killed_ids: [13, 37],
    },
    {
        slug: null,
        username: "s",
        player_id: 43,
        team_id: 15,
        time_alive: 47,
        rank: 7,
        died: true,
        kills: 0,
        damage_dealt: 35,
        damage_taken: 100,
        killer_id: 27,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Gilets Jaunes",
        player_id: 44,
        team_id: 15,
        time_alive: 213,
        rank: 7,
        died: true,
        kills: 1,
        damage_dealt: 101,
        damage_taken: 101,
        killer_id: 3,
        killed_ids: [27],
    },
    {
        slug: null,
        username: "___shoggoth___",
        player_id: 46,
        team_id: 15,
        time_alive: 204,
        rank: 7,
        died: true,
        kills: 2,
        damage_dealt: 423,
        damage_taken: 100,
        killer_id: 3,
        killed_ids: [26, 30],
    },
    {
        slug: null,
        username: "Anonimo 78",
        player_id: 45,
        team_id: 15,
        time_alive: 210,
        rank: 7,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 101,
        killer_id: 14,
        killed_ids: [],
    },
    {
        slug: "lazolvan",
        username: "lazolvan",
        player_id: 9,
        team_id: 3,
        time_alive: 220,
        rank: 8,
        died: true,
        kills: 5,
        damage_dealt: 707,
        damage_taken: 223,
        killer_id: 14,
        killed_ids: [50, 22, 75, 53, 65],
    },
    {
        slug: null,
        username: "Player",
        player_id: 10,
        team_id: 3,
        time_alive: 150,
        rank: 8,
        died: true,
        kills: 1,
        damage_dealt: 134,
        damage_taken: 227,
        killer_id: 14,
        killed_ids: [55],
    },
    {
        slug: null,
        username: "raptorizador",
        player_id: 11,
        team_id: 3,
        time_alive: 133,
        rank: 8,
        died: true,
        kills: 1,
        damage_dealt: 195,
        damage_taken: 100,
        killer_id: 65,
        killed_ids: [52],
    },
    {
        slug: null,
        username: "Player",
        player_id: 12,
        team_id: 3,
        time_alive: 124,
        rank: 8,
        died: true,
        kills: 1,
        damage_dealt: 227,
        damage_taken: 100,
        killer_id: 65,
        killed_ids: [73],
    },
    {
        slug: null,
        username: "QQQQQQQQQQQQQ",
        player_id: 5,
        team_id: 2,
        time_alive: 196,
        rank: 9,
        died: true,
        kills: 1,
        damage_dealt: 165,
        damage_taken: 101,
        killer_id: 61,
        killed_ids: [67],
    },
    {
        slug: "samet24",
        username: "mustafa",
        player_id: 7,
        team_id: 2,
        time_alive: 147,
        rank: 9,
        died: true,
        kills: 1,
        damage_dealt: 273,
        damage_taken: 100,
        killer_id: 2,
        killed_ids: [71],
    },
    {
        slug: null,
        username: "Player",
        player_id: 6,
        team_id: 2,
        time_alive: 196,
        rank: 9,
        died: true,
        kills: 0,
        damage_dealt: 34,
        damage_taken: 101,
        killer_id: 61,
        killed_ids: [],
    },
    {
        slug: "eduardo-galvan",
        username: "Player",
        player_id: 8,
        team_id: 2,
        time_alive: 56,
        rank: 9,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 67,
        killed_ids: [],
    },
    {
        slug: "mopkobka1",
        username: "MOPKOBKA",
        player_id: 37,
        team_id: 13,
        time_alive: 177,
        rank: 10,
        died: true,
        kills: 6,
        damage_dealt: 571,
        damage_taken: 320,
        killer_id: 68,
        killed_ids: [60, 25, 23, 56, 78, 63],
    },
    {
        slug: "rocket-wolf",
        username: "RockeT WolF",
        player_id: 65,
        team_id: 20,
        time_alive: 120,
        rank: 11,
        died: true,
        kills: 4,
        damage_dealt: 451,
        damage_taken: 102,
        killer_id: 9,
        killed_ids: [66, 12, 11, 24],
    },
    {
        slug: "youngmrazz",
        username: "youngmrazz",
        player_id: 63,
        team_id: 20,
        time_alive: 143,
        rank: 11,
        died: true,
        kills: 1,
        damage_dealt: 307,
        damage_taken: 145,
        killer_id: 37,
        killed_ids: [80],
    },
    {
        slug: "arrowman58",
        username: "ben türküm",
        player_id: 74,
        team_id: 25,
        time_alive: 110,
        rank: 12,
        died: true,
        kills: 1,
        damage_dealt: 293,
        damage_taken: 100,
        killer_id: 59,
        killed_ids: [38],
    },
    {
        slug: null,
        username: "hugo Lamo",
        player_id: 78,
        team_id: 26,
        time_alive: 90,
        rank: 13,
        died: true,
        kills: 0,
        damage_dealt: 45,
        damage_taken: 100,
        killer_id: 37,
        killed_ids: [],
    },
    {
        slug: "leamixem",
        username: "Player",
        player_id: 77,
        team_id: 26,
        time_alive: 58,
        rank: 13,
        died: true,
        kills: 0,
        damage_dealt: 77,
        damage_taken: 100,
        killer_id: 56,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Théo. Jrd",
        player_id: 80,
        team_id: 26,
        time_alive: 53,
        rank: 13,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 63,
        killed_ids: [],
    },
    {
        slug: "the-king-hk",
        username: "The King (HK)OKK",
        player_id: 79,
        team_id: 26,
        time_alive: 51,
        rank: 13,
        died: true,
        kills: 1,
        damage_dealt: 108,
        damage_taken: 101,
        killer_id: 61,
        killed_ids: [62],
    },
    {
        slug: null,
        username: "YOU",
        player_id: 21,
        team_id: 6,
        time_alive: 93,
        rank: 14,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 101,
        killer_id: 57,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Ahmad khan",
        player_id: 24,
        team_id: 6,
        time_alive: 126,
        rank: 14,
        died: true,
        kills: 2,
        damage_dealt: 207,
        damage_taken: 100,
        killer_id: 65,
        killed_ids: [76, 58],
    },
    {
        slug: null,
        username: "progamer",
        player_id: 20,
        team_id: 6,
        time_alive: 92,
        rank: 14,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 57,
        killed_ids: [],
    },
    {
        slug: null,
        username: "chica2011",
        player_id: 19,
        team_id: 6,
        time_alive: 121,
        rank: 14,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 56,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Amara",
        player_id: 58,
        team_id: 18,
        time_alive: 100,
        rank: 15,
        died: true,
        kills: 0,
        damage_dealt: 48,
        damage_taken: 124,
        killer_id: 24,
        killed_ids: [],
    },
    {
        slug: null,
        username: "kARA DEL1K",
        player_id: 57,
        team_id: 18,
        time_alive: 87,
        rank: 15,
        died: true,
        kills: 2,
        damage_dealt: 377,
        damage_taken: 100,
        killer_id: 14,
        killed_ids: [20, 21],
    },
    {
        slug: "kick-my-dick",
        username: "KICK MY DICK",
        player_id: 56,
        team_id: 18,
        time_alive: 103,
        rank: 15,
        died: true,
        kills: 2,
        damage_dealt: 287,
        damage_taken: 100,
        killer_id: 37,
        killed_ids: [77, 19],
    },
    {
        slug: null,
        username: "debil",
        player_id: 55,
        team_id: 18,
        time_alive: 96,
        rank: 15,
        died: true,
        kills: 1,
        damage_dealt: 265,
        damage_taken: 100,
        killer_id: 10,
        killed_ids: [29],
    },
    {
        slug: null,
        username: "365C:>",
        player_id: 52,
        team_id: 17,
        time_alive: 37,
        rank: 16,
        died: true,
        kills: 0,
        damage_dealt: 34,
        damage_taken: 100,
        killer_id: 11,
        killed_ids: [],
    },
    {
        slug: "maksmod",
        username: "YarikMod YT",
        player_id: 53,
        team_id: 17,
        time_alive: 93,
        rank: 16,
        died: true,
        kills: 1,
        damage_dealt: 152,
        damage_taken: 100,
        killer_id: 9,
        killed_ids: [72],
    },
    {
        slug: null,
        username: "Player",
        player_id: 50,
        team_id: 17,
        time_alive: 37,
        rank: 16,
        died: true,
        kills: 0,
        damage_dealt: 14,
        damage_taken: 100,
        killer_id: 9,
        killed_ids: [],
    },
    {
        slug: "lite_pixel",
        username: "gingerfaze",
        player_id: 54,
        team_id: 17,
        time_alive: 32,
        rank: 16,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 22,
        killed_ids: [],
    },
    {
        slug: null,
        username: "XXXSENSTAION4001",
        player_id: 76,
        team_id: 24,
        time_alive: 36,
        rank: 17,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 24,
        killed_ids: [],
    },
    {
        slug: "pozdrawiam1",
        username: "Pozdrawiam",
        player_id: 75,
        team_id: 24,
        time_alive: 67,
        rank: 17,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 9,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Player",
        player_id: 73,
        team_id: 24,
        time_alive: 67,
        rank: 17,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 12,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Player",
        player_id: 72,
        team_id: 24,
        time_alive: 72,
        rank: 17,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 101,
        killer_id: 53,
        killed_ids: [],
    },
    {
        slug: null,
        username: "team ?",
        player_id: 38,
        team_id: 10,
        time_alive: 57,
        rank: 18,
        died: true,
        kills: 0,
        damage_dealt: 77,
        damage_taken: 100,
        killer_id: 74,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Player",
        player_id: 28,
        team_id: 10,
        time_alive: 47,
        rank: 18,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 34,
        killed_ids: [],
    },
    {
        slug: null,
        username: "\u00110BO",
        player_id: 35,
        team_id: 10,
        time_alive: 85,
        rank: 18,
        died: true,
        kills: 0,
        damage_dealt: 7,
        damage_taken: 101,
        killer_id: 34,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Player",
        player_id: 36,
        team_id: 10,
        time_alive: 55,
        rank: 18,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 101,
        killer_id: 30,
        killed_ids: [],
    },
    {
        slug: null,
        username: "1090",
        player_id: 42,
        team_id: 14,
        time_alive: 69,
        rank: 19,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 30,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Player",
        player_id: 39,
        team_id: 14,
        time_alive: 82,
        rank: 19,
        died: true,
        kills: 1,
        damage_dealt: 172,
        damage_taken: 100,
        killer_id: 32,
        killed_ids: [16],
    },
    {
        slug: "foto4",
        username: "Der Tod",
        player_id: 40,
        team_id: 14,
        time_alive: 64,
        rank: 19,
        died: true,
        kills: 0,
        damage_dealt: 107,
        damage_taken: 100,
        killer_id: 30,
        killed_ids: [],
    },
    {
        slug: null,
        username: "1900000000000000",
        player_id: 41,
        team_id: 14,
        time_alive: 81,
        rank: 19,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 41,
        killed_ids: [],
    },
    {
        slug: "fearfullwarrior_",
        username: "fearfullwarrior",
        player_id: 66,
        team_id: 21,
        time_alive: 31,
        rank: 20,
        died: true,
        kills: 0,
        damage_dealt: 26,
        damage_taken: 100,
        killer_id: 65,
        killed_ids: [],
    },
    {
        slug: null,
        username: "5:0B5@8=1C@3",
        player_id: 71,
        team_id: 21,
        time_alive: 37,
        rank: 20,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 7,
        killed_ids: [],
    },
    {
        slug: "p3izer",
        username: "YTPRO",
        player_id: 64,
        team_id: 21,
        time_alive: 61,
        rank: 20,
        died: true,
        kills: 0,
        damage_dealt: 141,
        damage_taken: 100,
        killer_id: 64,
        killed_ids: [],
    },
    {
        slug: "khe1",
        username: "Khé",
        player_id: 67,
        team_id: 21,
        time_alive: 50,
        rank: 20,
        died: true,
        kills: 1,
        damage_dealt: 172,
        damage_taken: 101,
        killer_id: 5,
        killed_ids: [8],
    },
    {
        slug: null,
        username: "Player",
        player_id: 17,
        team_id: 5,
        time_alive: 47,
        rank: 21,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 3,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Sasa43",
        player_id: 18,
        team_id: 5,
        time_alive: 82,
        rank: 21,
        died: true,
        kills: 0,
        damage_dealt: 12,
        damage_taken: 101,
        killer_id: 3,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Cacita",
        player_id: 26,
        team_id: 9,
        time_alive: 75,
        rank: 22,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 101,
        killer_id: 46,
        killed_ids: [],
    },
    {
        slug: "fetroxito",
        username: "spayk plus  pro",
        player_id: 27,
        team_id: 9,
        time_alive: 77,
        rank: 22,
        died: true,
        kills: 1,
        damage_dealt: 217,
        damage_taken: 101,
        killer_id: 44,
        killed_ids: [43],
    },
    {
        slug: "roro43",
        username: "Rrrrrroberto",
        player_id: 22,
        team_id: 7,
        time_alive: 71,
        rank: 23,
        died: true,
        kills: 1,
        damage_dealt: 287,
        damage_taken: 100,
        killer_id: 9,
        killed_ids: [54],
    },
    {
        slug: null,
        username: "Player",
        player_id: 25,
        team_id: 8,
        time_alive: 64,
        rank: 24,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 37,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Erolcan",
        player_id: 23,
        team_id: 8,
        time_alive: 66,
        rank: 24,
        died: true,
        kills: 0,
        damage_dealt: 152,
        damage_taken: 101,
        killer_id: 37,
        killed_ids: [],
    },
    {
        slug: null,
        username: "derilius",
        player_id: 70,
        team_id: 23,
        time_alive: 30,
        rank: 25,
        died: true,
        kills: 0,
        damage_dealt: 17,
        damage_taken: 100,
        killer_id: 3,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Przemo",
        player_id: 69,
        team_id: 23,
        time_alive: 30,
        rank: 25,
        died: true,
        kills: 0,
        damage_dealt: 16,
        damage_taken: 100,
        killer_id: 3,
        killed_ids: [],
    },
    {
        slug: null,
        username: "andreas",
        player_id: 29,
        team_id: 11,
        time_alive: 47,
        rank: 26,
        died: true,
        kills: 0,
        damage_dealt: 37,
        damage_taken: 101,
        killer_id: 55,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Lucas",
        player_id: 33,
        team_id: 11,
        time_alive: 47,
        rank: 26,
        died: true,
        kills: 0,
        damage_dealt: 110,
        damage_taken: 100,
        killer_id: 33,
        killed_ids: [],
    },
];

const two: MatchData[] = [
    {
        slug: "oooboje",
        username: "oooboje",
        player_id: 36,
        team_id: 12,
        time_alive: 380,
        rank: 1,
        died: false,
        kills: 5,
        damage_dealt: 660,
        damage_taken: 425,
        killer_id: 0,
        killed_ids: [23, 40, 74, 73, 60],
    },
    {
        slug: "ambaa",
        username: "AmbaA",
        player_id: 35,
        team_id: 12,
        time_alive: 194,
        rank: 1,
        died: true,
        kills: 1,
        damage_dealt: 658,
        damage_taken: 170,
        killer_id: 1,
        killed_ids: [2],
    },
    {
        slug: "italiano2",
        username: "_/\\_|-|__|-|_/\\_",
        player_id: 34,
        team_id: 12,
        time_alive: 380,
        rank: 1,
        died: false,
        kills: 9,
        damage_dealt: 849,
        damage_taken: 278,
        killer_id: 0,
        killed_ids: [21, 64, 55, 54, 9, 8, 1, 39, 41],
    },
    {
        slug: "samet24",
        username: "mustafa",
        player_id: 57,
        team_id: 18,
        time_alive: 109,
        rank: 2,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 101,
        killer_id: 62,
        killed_ids: [],
    },
    {
        slug: null,
        username: "d",
        player_id: 64,
        team_id: 18,
        time_alive: 45,
        rank: 2,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 34,
        killed_ids: [],
    },
    {
        slug: null,
        username: "228",
        player_id: 61,
        team_id: 18,
        time_alive: 148,
        rank: 2,
        died: true,
        kills: 1,
        damage_dealt: 136,
        damage_taken: 100,
        killer_id: 62,
        killed_ids: [53],
    },
    {
        slug: null,
        username: "KuratiStvor",
        player_id: 60,
        team_id: 18,
        time_alive: 364,
        rank: 2,
        died: true,
        kills: 2,
        damage_dealt: 295,
        damage_taken: 222,
        killer_id: 36,
        killed_ids: [78, 62],
    },
    {
        slug: "shiny_fox",
        username: "{SW}FallenAngel",
        player_id: 74,
        team_id: 23,
        time_alive: 280,
        rank: 3,
        died: true,
        kills: 3,
        damage_dealt: 722,
        damage_taken: 265,
        killer_id: 36,
        killed_ids: [20, 19, 42],
    },
    {
        slug: "team-kirill2007",
        username: "Bouchik {SW}",
        player_id: 71,
        team_id: 23,
        time_alive: 146,
        rank: 3,
        died: true,
        kills: 1,
        damage_dealt: 177,
        damage_taken: 100,
        killer_id: 50,
        killed_ids: [51],
    },
    {
        slug: null,
        username: "Kiss {SW}",
        player_id: 75,
        team_id: 23,
        time_alive: 43,
        rank: 3,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 23,
        killed_ids: [],
    },
    {
        slug: "yte",
        username: "cziesnok",
        player_id: 73,
        team_id: 23,
        time_alive: 321,
        rank: 3,
        died: true,
        kills: 3,
        damage_dealt: 503,
        damage_taken: 290,
        killer_id: 36,
        killed_ids: [50, 25, 27],
    },
    {
        slug: "tuckar",
        username: "Buddy",
        player_id: 39,
        team_id: 13,
        time_alive: 268,
        rank: 4,
        died: true,
        kills: 3,
        damage_dealt: 466,
        damage_taken: 236,
        killer_id: 34,
        killed_ids: [15, 17, 38],
    },
    {
        slug: null,
        username: "RIC PITINO PAO13",
        player_id: 40,
        team_id: 13,
        time_alive: 267,
        rank: 4,
        died: true,
        kills: 1,
        damage_dealt: 260,
        damage_taken: 115,
        killer_id: 36,
        killed_ids: [33],
    },
    {
        slug: null,
        username: "adam tabornok",
        player_id: 42,
        team_id: 13,
        time_alive: 267,
        rank: 4,
        died: true,
        kills: 0,
        damage_dealt: 19,
        damage_taken: 199,
        killer_id: 74,
        killed_ids: [],
    },
    {
        slug: null,
        username: "YEET",
        player_id: 41,
        team_id: 13,
        time_alive: 267,
        rank: 4,
        died: true,
        kills: 0,
        damage_dealt: 39,
        damage_taken: 200,
        killer_id: 34,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Pro",
        player_id: 24,
        team_id: 9,
        time_alive: 114,
        rank: 5,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 0,
        killed_ids: [],
    },
    {
        slug: "kirill156",
        username: "Kirill",
        player_id: 25,
        team_id: 9,
        time_alive: 222,
        rank: 5,
        died: true,
        kills: 1,
        damage_dealt: 247,
        damage_taken: 219,
        killer_id: 73,
        killed_ids: [47],
    },
    {
        slug: "hhhhhhhhhhhhhhhh10",
        username: "ALSANA BOMBE",
        player_id: 26,
        team_id: 9,
        time_alive: 81,
        rank: 5,
        died: true,
        kills: 0,
        damage_dealt: 61,
        damage_taken: 100,
        killer_id: 37,
        killed_ids: [],
    },
    {
        slug: "timur-pro",
        username: '²:>\u0018\u001f \u001c"ö',
        player_id: 27,
        team_id: 9,
        time_alive: 241,
        rank: 5,
        died: true,
        kills: 1,
        damage_dealt: 143,
        damage_taken: 180,
        killer_id: 73,
        killed_ids: [37],
    },
    {
        slug: "evzinplay",
        username: "~ggman:D~ {SW}",
        player_id: 62,
        team_id: 20,
        time_alive: 208,
        rank: 6,
        died: true,
        kills: 3,
        damage_dealt: 542,
        damage_taken: 176,
        killer_id: 60,
        killed_ids: [77, 57, 61],
    },
    {
        slug: "jackubson1",
        username: "Jackubson",
        player_id: 37,
        team_id: 11,
        time_alive: 96,
        rank: 7,
        died: true,
        kills: 2,
        damage_dealt: 353,
        damage_taken: 101,
        killer_id: 27,
        killed_ids: [7, 26],
    },
    {
        slug: null,
        username: "pro",
        player_id: 38,
        team_id: 11,
        time_alive: 217,
        rank: 7,
        died: true,
        kills: 0,
        damage_dealt: 42,
        damage_taken: 156,
        killer_id: 39,
        killed_ids: [],
    },
    {
        slug: "eduardo-galvan",
        username: "Player",
        player_id: 33,
        team_id: 11,
        time_alive: 208,
        rank: 7,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 40,
        killed_ids: [],
    },
    {
        slug: "jugurtha-le-fr",
        username: "COUCOU LES FR",
        player_id: 32,
        team_id: 11,
        time_alive: 77,
        rank: 7,
        died: true,
        kills: 1,
        damage_dealt: 298,
        damage_taken: 100,
        killer_id: 72,
        killed_ids: [76],
    },
    {
        slug: "trytonx",
        username: "privet",
        player_id: 1,
        team_id: 1,
        time_alive: 228,
        rank: 8,
        died: true,
        kills: 9,
        damage_dealt: 1347,
        damage_taken: 141,
        killer_id: 34,
        killed_ids: [31, 28, 29, 30, 70, 65, 66, 67, 35],
    },
    {
        slug: null,
        username: "Gergo13816",
        player_id: 5,
        team_id: 1,
        time_alive: 162,
        rank: 8,
        died: true,
        kills: 2,
        damage_dealt: 317,
        damage_taken: 100,
        killer_id: 11,
        killed_ids: [12, 6],
    },
    {
        slug: null,
        username: "Bence 723655",
        player_id: 3,
        team_id: 1,
        time_alive: 151,
        rank: 8,
        died: true,
        kills: 0,
        damage_dealt: 33,
        damage_taken: 200,
        killer_id: 65,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Player",
        player_id: 2,
        team_id: 1,
        time_alive: 192,
        rank: 8,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 35,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Pro1st",
        player_id: 18,
        team_id: 6,
        time_alive: 198,
        rank: 9,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 0,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Player",
        player_id: 17,
        team_id: 6,
        time_alive: 138,
        rank: 9,
        died: true,
        kills: 0,
        damage_dealt: 28,
        damage_taken: 101,
        killer_id: 39,
        killed_ids: [],
    },
    {
        slug: "pro1st",
        username: "Player",
        player_id: 15,
        team_id: 6,
        time_alive: 134,
        rank: 9,
        died: true,
        kills: 0,
        damage_dealt: 5,
        damage_taken: 100,
        killer_id: 39,
        killed_ids: [],
    },
    {
        slug: "tarix-nikotin",
        username: "Toxic_Nikotin",
        player_id: 51,
        team_id: 16,
        time_alive: 156,
        rank: 10,
        died: true,
        kills: 4,
        damage_dealt: 509,
        damage_taken: 150,
        killer_id: 71,
        killed_ids: [45, 46, 4, 72],
    },
    {
        slug: "beautifullworld",
        username: "Lucky Fork",
        player_id: 50,
        team_id: 16,
        time_alive: 156,
        rank: 10,
        died: true,
        kills: 8,
        damage_dealt: 1168,
        damage_taken: 165,
        killer_id: 73,
        killed_ids: [43, 44, 68, 69, 49, 52, 48, 71],
    },
    {
        slug: null,
        username: "Lucas",
        player_id: 66,
        team_id: 21,
        time_alive: 138,
        rank: 11,
        died: true,
        kills: 1,
        damage_dealt: 127,
        damage_taken: 100,
        killer_id: 1,
        killed_ids: [63],
    },
    {
        slug: null,
        username: "Cnzo",
        player_id: 70,
        team_id: 21,
        time_alive: 134,
        rank: 11,
        died: true,
        kills: 0,
        damage_dealt: 19,
        damage_taken: 201,
        killer_id: 1,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Thomas",
        player_id: 67,
        team_id: 21,
        time_alive: 137,
        rank: 11,
        died: true,
        kills: 1,
        damage_dealt: 195,
        damage_taken: 100,
        killer_id: 1,
        killed_ids: [10],
    },
    {
        slug: "samuel354",
        username: "Samuel",
        player_id: 65,
        team_id: 21,
        time_alive: 138,
        rank: 11,
        died: true,
        kills: 6,
        damage_dealt: 818,
        damage_taken: 207,
        killer_id: 1,
        killed_ids: [16, 58, 14, 13, 11, 3],
    },
    {
        slug: null,
        username: "Player",
        player_id: 52,
        team_id: 15,
        time_alive: 135,
        rank: 12,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 50,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Why? Why? Why?",
        player_id: 47,
        team_id: 15,
        time_alive: 78,
        rank: 12,
        died: true,
        kills: 0,
        damage_dealt: 90,
        damage_taken: 100,
        killer_id: 25,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Player",
        player_id: 49,
        team_id: 15,
        time_alive: 128,
        rank: 12,
        died: true,
        kills: 1,
        damage_dealt: 189,
        damage_taken: 100,
        killer_id: 50,
        killed_ids: [22],
    },
    {
        slug: null,
        username: "Player",
        player_id: 48,
        team_id: 15,
        time_alive: 139,
        rank: 12,
        died: true,
        kills: 0,
        damage_dealt: 6,
        damage_taken: 136,
        killer_id: 50,
        killed_ids: [],
    },
    {
        slug: "pauljrc1803",
        username: "Pauljrc1803",
        player_id: 11,
        team_id: 2,
        time_alive: 133,
        rank: 13,
        died: true,
        kills: 1,
        damage_dealt: 118,
        damage_taken: 101,
        killer_id: 65,
        killed_ids: [5],
    },
    {
        slug: "egor102",
        username: "OPTIKOT",
        player_id: 7,
        team_id: 2,
        time_alive: 58,
        rank: 13,
        died: true,
        kills: 0,
        damage_dealt: 45,
        damage_taken: 100,
        killer_id: 37,
        killed_ids: [],
    },
    {
        slug: "dor5",
        username: "\u0018A015:",
        player_id: 6,
        team_id: 2,
        time_alive: 134,
        rank: 13,
        died: true,
        kills: 0,
        damage_dealt: 126,
        damage_taken: 101,
        killer_id: 5,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Real Madrid",
        player_id: 4,
        team_id: 2,
        time_alive: 66,
        rank: 13,
        died: true,
        kills: 0,
        damage_dealt: 18,
        damage_taken: 101,
        killer_id: 51,
        killed_ids: [],
    },
    {
        slug: null,
        username: "170000000000000",
        player_id: 30,
        team_id: 10,
        time_alive: 124,
        rank: 14,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 1,
        killed_ids: [],
    },
    {
        slug: null,
        username: "KUDYDUDYE",
        player_id: 31,
        team_id: 10,
        time_alive: 90,
        rank: 14,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 101,
        killer_id: 1,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Baxtrix (EN)",
        player_id: 28,
        team_id: 10,
        time_alive: 94,
        rank: 14,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 101,
        killer_id: 1,
        killed_ids: [],
    },
    {
        slug: null,
        username: "thanh vn",
        player_id: 29,
        team_id: 10,
        time_alive: 124,
        rank: 14,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 1,
        killed_ids: [],
    },
    {
        slug: null,
        username: "kARA DEL1K",
        player_id: 56,
        team_id: 17,
        time_alive: 79,
        rank: 15,
        died: true,
        kills: 0,
        damage_dealt: 26,
        damage_taken: 100,
        killer_id: 8,
        killed_ids: [],
    },
    {
        slug: null,
        username: "saba",
        player_id: 55,
        team_id: 17,
        time_alive: 72,
        rank: 15,
        died: true,
        kills: 1,
        damage_dealt: 192,
        damage_taken: 102,
        killer_id: 34,
        killed_ids: [59],
    },
    {
        slug: null,
        username: "gio",
        player_id: 54,
        team_id: 17,
        time_alive: 73,
        rank: 15,
        died: true,
        kills: 0,
        damage_dealt: 14,
        damage_taken: 100,
        killer_id: 34,
        killed_ids: [],
    },
    {
        slug: null,
        username: "1090",
        player_id: 53,
        team_id: 17,
        time_alive: 110,
        rank: 15,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 61,
        killed_ids: [],
    },
    {
        slug: "majkel-kamszot",
        username: "Majkel Kamszot",
        player_id: 8,
        team_id: 3,
        time_alive: 128,
        rank: 16,
        died: true,
        kills: 1,
        damage_dealt: 232,
        damage_taken: 101,
        killer_id: 34,
        killed_ids: [56],
    },
    {
        slug: "dziki1",
        username: "dziki",
        player_id: 9,
        team_id: 3,
        time_alive: 128,
        rank: 16,
        died: true,
        kills: 0,
        damage_dealt: 73,
        damage_taken: 112,
        killer_id: 34,
        killed_ids: [],
    },
    {
        slug: "amorti",
        username: "amorti",
        player_id: 13,
        team_id: 5,
        time_alive: 122,
        rank: 17,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 65,
        killed_ids: [],
    },
    {
        slug: "enes94",
        username: "Enes",
        player_id: 14,
        team_id: 5,
        time_alive: 99,
        rank: 17,
        died: true,
        kills: 0,
        damage_dealt: 119,
        damage_taken: 100,
        killer_id: 65,
        killed_ids: [],
    },
    {
        slug: null,
        username: "BeratDAYI",
        player_id: 16,
        team_id: 5,
        time_alive: 40,
        rank: 17,
        died: true,
        kills: 0,
        damage_dealt: 29,
        damage_taken: 100,
        killer_id: 65,
        killed_ids: [],
    },
    {
        slug: null,
        username: "Rigby",
        player_id: 12,
        team_id: 5,
        time_alive: 122,
        rank: 17,
        died: true,
        kills: 0,
        damage_dealt: 155,
        damage_taken: 100,
        killer_id: 5,
        killed_ids: [],
    },
    {
        slug: "mr-perets",
        username: "Prop4ik",
        player_id: 20,
        team_id: 7,
        time_alive: 64,
        rank: 18,
        died: true,
        kills: 0,
        damage_dealt: 65,
        damage_taken: 100,
        killer_id: 74,
        killed_ids: [],
    },
    {
        slug: null,
        username: "esmael+",
        player_id: 22,
        team_id: 7,
        time_alive: 88,
        rank: 18,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 49,
        killed_ids: [],
    },
    {
        slug: null,
        username: "I Love you",
        player_id: 23,
        team_id: 7,
        time_alive: 98,
        rank: 18,
        died: true,
        kills: 1,
        damage_dealt: 196,
        damage_taken: 100,
        killer_id: 36,
        killed_ids: [75],
    },
    {
        slug: null,
        username: "noob",
        player_id: 19,
        team_id: 7,
        time_alive: 85,
        rank: 18,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 74,
        killed_ids: [],
    },
    {
        slug: "prosto_surviv",
        username: "Iv",
        player_id: 72,
        team_id: 22,
        time_alive: 58,
        rank: 19,
        died: true,
        kills: 1,
        damage_dealt: 84,
        damage_taken: 100,
        killer_id: 51,
        killed_ids: [32],
    },
    {
        slug: null,
        username: "Player ;I",
        player_id: 76,
        team_id: 22,
        time_alive: 50,
        rank: 19,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 32,
        killed_ids: [],
    },
    {
        slug: null,
        username: "\u001cv\u001eLimbo \u001cv\u001e -",
        player_id: 69,
        team_id: 22,
        time_alive: 61,
        rank: 19,
        died: true,
        kills: 0,
        damage_dealt: 60,
        damage_taken: 100,
        killer_id: 50,
        killed_ids: [],
    },
    {
        slug: null,
        username: "^-^$D*A*N^-^$",
        player_id: 68,
        team_id: 22,
        time_alive: 61,
        rank: 19,
        died: true,
        kills: 0,
        damage_dealt: 31,
        damage_taken: 100,
        killer_id: 50,
        killed_ids: [],
    },
    {
        slug: "foczyslaw",
        username: "Foczyslaw pl",
        player_id: 78,
        team_id: 25,
        time_alive: 48,
        rank: 20,
        died: true,
        kills: 0,
        damage_dealt: 40,
        damage_taken: 100,
        killer_id: 60,
        killed_ids: [],
    },
    {
        slug: null,
        username: "R.S1010",
        player_id: 10,
        team_id: 4,
        time_alive: 79,
        rank: 21,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 67,
        killed_ids: [],
    },
    {
        slug: null,
        username: "\u001bØá",
        player_id: 63,
        team_id: 19,
        time_alive: 35,
        rank: 22,
        died: true,
        kills: 0,
        damage_dealt: 117,
        damage_taken: 100,
        killer_id: 66,
        killed_ids: [],
    },
    {
        slug: "faratheripper",
        username: "FARAON.PRO",
        player_id: 59,
        team_id: 19,
        time_alive: 24,
        rank: 22,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 101,
        killer_id: 55,
        killed_ids: [],
    },
    {
        slug: "semen7",
        username: "KPOBb",
        player_id: 58,
        team_id: 19,
        time_alive: 36,
        rank: 22,
        died: true,
        kills: 0,
        damage_dealt: 32,
        damage_taken: 102,
        killer_id: 65,
        killed_ids: [],
    },
    {
        slug: null,
        username: "arteom",
        player_id: 45,
        team_id: 14,
        time_alive: 38,
        rank: 23,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 101,
        killer_id: 51,
        killed_ids: [],
    },
    {
        slug: null,
        username: "40=8; AC?5@ ?@>",
        player_id: 43,
        team_id: 14,
        time_alive: 39,
        rank: 23,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 50,
        killed_ids: [],
    },
    {
        slug: null,
        username: "warnix656",
        player_id: 44,
        team_id: 14,
        time_alive: 39,
        rank: 23,
        died: true,
        kills: 0,
        damage_dealt: 0,
        damage_taken: 100,
        killer_id: 50,
        killed_ids: [],
    },
    {
        slug: null,
        username: "www",
        player_id: 46,
        team_id: 14,
        time_alive: 38,
        rank: 23,
        died: true,
        kills: 0,
        damage_dealt: 59,
        damage_taken: 100,
        killer_id: 51,
        killed_ids: [],
    },
    {
        slug: "aimm",
        username: "NAGIBATOR RUSSIA",
        player_id: 77,
        team_id: 24,
        time_alive: 20,
        rank: 24,
        died: true,
        kills: 0,
        damage_dealt: 57,
        damage_taken: 100,
        killer_id: 62,
        killed_ids: [],
    },
    {
        slug: "bag-master-eu",
        username: "eu 20 pls",
        player_id: 21,
        team_id: 8,
        time_alive: 49,
        rank: 25,
        died: true,
        kills: 0,
        damage_dealt: 71,
        damage_taken: 119,
        killer_id: 34,
        killed_ids: [],
    },
];
